name: Tempo Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test-tempo:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the parquet-go repository
      - name: Checkout parquet-go
        uses: actions/checkout@v3

      # Step 2: Clone the Tempo repository
      - name: Clone Tempo
        run: git clone https://github.com/grafana/tempo.git

      # Step 3: Set up Go (if not already set up in the runner)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Use the appropriate Go version for Tempo

      # Step 4: Replace parquet-go with the local version
      - name: Replace parquet-go with local version
        run: |
          cd tempo
          go mod edit -replace github.com/parquet-go/parquet-go=../parquet-go

      # Step 5: Run critical Tempo tests
      - name: Run Critical Tempo Tests
        run: |
          cd tempo
          go test ./tempodb/encoding/vparquet4/...
          go test ./tempodb/wal/...
          go test ./tempodb/...
